#
version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.11-browsers
    steps:
    - checkout
    - attach_workspace:
        at: ~/repo/tmp
    - run:
        name:  Download cc-test-reporter
        command: |
          mkdir -p tmp/
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
          chmod +x ./tmp/cc-test-reporter
    - persist_to_workspace:
        root: tmp
        paths:
        - cc-test-reporter
    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: npm install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run: npm run lint
    - run:
        name: Run frontend tests
        command: |
          npm run test-headless --code-coverage
          pwd
          ls -al
          ls -al tmp
          ls -al src
          ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/codeclimate.frontend.json src/coverage/lcov.info
    - run:
        name: Upload coverage results to Code Climate
        command: |
              ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.frontend.json
